# Generated by Django 6.0.1 on 2026-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=10000),
        ),
    ]
